name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    
    - name: Install dependencies
      run: |
        gem install bundler -v 2.4.22
        bundle install
      
    - name: Build Jekyll
      run: bundle exec jekyll build
      
    - name: Commit built files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b build
        git add .
        git commit -m "Build Jekyll site"
        git push origin build
